welcome:
  enable: true
  message:
    - "&a&lДобро пожаловать на сервер!"
    - "&7Чтобы начать играть, пожалуйста:"
    - "&7- &a/register <пароль> <повтор пароля> &7- если вы новый игрок"
    - "&7- &a/login <пароль> &7- если вы уже зарегистрированы"
    - "&7При возникновении проблем обращайтесь к администрации"

connect:
  enable: true
  name-server: "main"

spawn:
  x: -5
  y: 1
  z: 1
  yaw: -180
  pitch: 0